### ISSUE TITLE
Trying to build actual version

### ISSUE THREAD

**Issue by tomtera** [Krever/scala-startup-template#1]
Dear Wojciech,
after checking out endpoints from Julien RF I found your work here but faced minor problems when building the current version... Especially the ApiBase is missing the algebra.Builders and algebra.JsonBuilders types.
Do you have an idea regarding this?

Kind regards
Volker

**Comment by Krever** [comment]
Hi @tomtera , I'm very happy to see some interest. The problems you are facing come from the fact that I was trying to use the version of the endpoints that was not merged into master because it requires some more work(https://github.com/julienrf/endpoints/pull/47). Migration to the current stable version should be really straight forward. I can probably do that in next few days or you can try to do it on your own as an exercise.

**Comment by tomtera** [comment]
Hi @Krever,
yes, your project is very promising for my concerns and I'm looking forward to your progress in future!
And: yes, I will try to do the migration myself but still need to do a "walk thru the code" to understand more than I do now. Maybe I will manage it, otherwise I wait for your progress!

**Comment by Krever** [comment]
I have migrated to the stable version of endpoints and also added some docs on how to run the project.

**Comment by tomtera** [comment]
This is really great, thanks for your support! I check this out now.
